### ISSUE TITLE
Request for local model loading script modification.

### ISSUE THREAD

**Issue by GenTxt** [GOAT-AI-lab/GOAT-Storytelling-Agent#1]
Your code and model looks great for its intended use (as per the posted examples and 'prompts.py') and has already been quantized here: https://huggingface.co/TheBloke/GOAT-70B-Storytelling-GGUF (other formats and quantization levels available)

Unfortunately the requirement for a paid endpoint prevents running your complete pipeline script although your original model loads fine in 4bit via textgeneration webui and other python transformer scripts.

I've tried editing ENDPOINT and 'requests.post' to load a local model but with no success. I'm sure I speak for other users who would appreciate loading a local version of your model and running the modified script.

Cheers

**Comment by KerfuffleV2** [comment]
@GenTxt You can actually just change the tokenizer path to point at GOAT's HF repo itself instead of the Meta one that requires authentication.

In `storytelling_agent.py`:

```python
tokenizer = LlamaTokenizerFast.from_pretrained(
    "GOAT-AI/GOAT-70B-Storytelling", token=HF_ACCESS_TOKEN)
```

In `config.py` just set `HF_ACCESS_TOKEN` to `None`.

I also had to change the imports in `storytelling_agent.py` from:

```python
from src import prompts, utils
from src.config import ENDPOINT, HF_ACCESS_TOKEN
from src.plan import Plan
```

to

```python
from . import prompts, utils
from .config import ENDPOINT, HF_ACCESS_TOKEN
from .plan import Plan
```

Note: I'm not affiliated with the repo owner.

**Comment by GenTxt** [comment]
Thanks for the reply and help.
Still having issue with pointing ENDPOINT = to local model folder.
Just downloaded your fork and ran through the readme instructions.
No errors but it doesn't execute beyond the last >>>

$ python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from goat_storytelling_agent import storytelling_agent as goat
>>> novel_scenes = goat.generate_story('treasure hunt in a jungle', form='novel')
>>> ???

Is there another command to enter?

Simply want to load the default fp16 model in 4bits using something like:

model = AutoModelForCausalLM.from_pretrained(model_name, device_map='auto', load_in_4bit=True, torch_dtype=torch.float16)

as per numerous other transformers scripts

thanks

**Comment by KerfuffleV2** [comment]
> Still having issue with pointing ENDPOINT = to local model folder.

Sorry, I wasn't really clear. My fork basically just makes it so you don't need to auth if you're using a HF endpoint, it doesn't add anything to let you directly load a HF model inside the GOAT stuff.

I'm not sure if HF has something to provide serve a model with their endpoint type stuff. If so, you can run that separately to serve the model, then point the endpoint for GOAT at that.

I actually can't really use HF models since my GPU is garbage, so my testing has been focused on using `llama.cpp`'s `server` example to serve the model. I don't know if that's an option for you, you'd need to download a GGUF model to use.

**Comment by KerfuffleV2** [comment]
This may or may not help you. Assuming you're using my fork:

```python
from time import time
from goat_storytelling_agent import storytelling_agent as goat

def main():
    seed = int(time())
    seed = 1700596031
    print(f"Using seed: {seed}")
    agent = goat.StoryAgent('Story premise here',
        form='short story', 
        backend="llama.cpp",
        backend_uri="http://127.0.0.1:8080/",
        max_tokens=8000,
        request_timeout=600,
        n_crop_previous=600,
        extra_options=dict(seed=seed, temperature=0.9, top_k=0, top_p=1.0, min_p=0.3, stop=["### USER", "### ASSISTANT"]),
        scene_extra_options= dict(temperature = 1.2, min_p = 0.15))
    novel_scenes = agent.generate_story()
    print()
    print(novel_scenes)

if __name__ == "__main__":
    main()
```

Note that `backend="llama.cpp"` so that expects to be pointed at a `llama.cpp` endpoint (the `server` example in `llama.cpp`). If you want to use a HuggingFace endpoint then you need to set `backend="hf"` and also use the correct URI format for HF endpoints (no idea what it should look like really).

If you know enough Python, you could also write a very simple wrapper that loads a model and serves it. You just have to accept and respond with JSON. The request format looks like:

```json
{"input": "prompt text here", "parameters": {"max_new_tokens": 123}}
```

And you just have to respond with a JSON object like

```json
{"generated_text": "Results of generation here"}
```

So you can just use a really simple HTTP server like: https://docs.python.org/3/library/http.server.html

And hook that up to submit the request to the model and return the response in the format I showed. You'd have to run your model in a separate process, but it would be local and free.

**Comment by GenTxt** [comment]
Thanks for the update. I'll work through this. I have gguf models I can load through textgeneration webui and I've tried pointing to http://127.0.0.1:7860/ which is the address textgen uses. Model loading is fine but calling via the original GOAT script generates a series of 'timed out' messages before exiting.

**Comment by KerfuffleV2** [comment]
> Model loading is fine but calling via the original GOAT script generates a series of 'timed out' messages before exiting.

I don't know what format text generation webui uses, it's probably different from `server`. This is what I was talking about: https://github.com/ggerganov/llama.cpp/tree/master/examples/server

You can just use that to load a GGUF model. Just for example, this is what I ran:

    ./server --rope-scaling yarn -c 8200 --rope-freq-scale .5 -m /blah/goat-70b-storytelling.Q4_K_S.gguf --mlock -np 3

You can remove the RoPE stuff if you want, but that basically lets you double the context size from 4096 to 8192. That example runs entirely on the CPU, so you can try using `-ngl N` where N is the number of layers you want to offload to GPU. 8k context takes a fair amount of VRAM by itself just for the prompt processing though so it's unlikely you'll be able to offload the whole model.

**Comment by alisher-amantay** [comment]
I have solved most issues like tokenizer access token, module loading, quantized version support in #6 . As per your last issue with timeout, please confirm you can get your text generation server to generate 4096 token long outputs and could you report how long that takes? It could be that the quantized version even is too slow and gives a timeout. If that's not the issue we need to find the trouble causing place.

**Comment by GenTxt** [comment]
Thanks to both of you for detailed instructions, examples, and updates. Have script and Q4 .gguf model currently running with llama server.

Tweaking gpu load to prevent OOM but besides that everything is working great.

Closing on my end.

Cheers
